package com.json.web.entity;

public class AlertCompareProcessStatus {

	/**
	 * 处理状态响应
	 */

/*	private static final String ALERT_COMPARE_PROCESS_STATUS_UNKNOWN = "未知状态";
	private static final String ALERT_COMPARE_PROCESS_STATUS_NO_PROCESS = "未处理";
	private static final String ALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT = "误报";
	private static final String ALERT_COMPARE_PROCESS_STATUS_PASS = "放行";
	private static final String ALERT_COMPARE_PROCESS_STATUS_RETURN = "劝返";
	private static final String ALERT_COMPARE_PROCESS_STATUS_CATCH = "抓捕";
	private static final String ALERT_COMPARE_PROCESS_STATUS_ALL = "所有处理状态";*/
	
	
	private  String ALERT_COMPARE_PROCESS_STATUS_UNKNOWN ;
	private  String ALERT_COMPARE_PROCESS_STATUS_NO_PROCESS ;
	private  String ALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT ;
	private  String ALERT_COMPARE_PROCESS_STATUS_PASS ;
	private  String ALERT_COMPARE_PROCESS_STATUS_RETURN ;
	private  String ALERT_COMPARE_PROCESS_STATUS_CATCH ;
	private  String ALERT_COMPARE_PROCESS_STATUS_ALL ;
	
	
	public String getALERT_COMPARE_PROCESS_STATUS_UNKNOWN() {
		return ALERT_COMPARE_PROCESS_STATUS_UNKNOWN;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_UNKNOWN(String aLERT_COMPARE_PROCESS_STATUS_UNKNOWN) {
		ALERT_COMPARE_PROCESS_STATUS_UNKNOWN = aLERT_COMPARE_PROCESS_STATUS_UNKNOWN;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_NO_PROCESS() {
		return ALERT_COMPARE_PROCESS_STATUS_NO_PROCESS;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_NO_PROCESS(String aLERT_COMPARE_PROCESS_STATUS_NO_PROCESS) {
		ALERT_COMPARE_PROCESS_STATUS_NO_PROCESS = aLERT_COMPARE_PROCESS_STATUS_NO_PROCESS;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT() {
		return ALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT(String aLERT_COMPARE_PROCESS_STATUS_FALSE_ALERT) {
		ALERT_COMPARE_PROCESS_STATUS_FALSE_ALERT = aLERT_COMPARE_PROCESS_STATUS_FALSE_ALERT;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_PASS() {
		return ALERT_COMPARE_PROCESS_STATUS_PASS;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_PASS(String aLERT_COMPARE_PROCESS_STATUS_PASS) {
		ALERT_COMPARE_PROCESS_STATUS_PASS = aLERT_COMPARE_PROCESS_STATUS_PASS;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_RETURN() {
		return ALERT_COMPARE_PROCESS_STATUS_RETURN;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_RETURN(String aLERT_COMPARE_PROCESS_STATUS_RETURN) {
		ALERT_COMPARE_PROCESS_STATUS_RETURN = aLERT_COMPARE_PROCESS_STATUS_RETURN;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_CATCH() {
		return ALERT_COMPARE_PROCESS_STATUS_CATCH;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_CATCH(String aLERT_COMPARE_PROCESS_STATUS_CATCH) {
		ALERT_COMPARE_PROCESS_STATUS_CATCH = aLERT_COMPARE_PROCESS_STATUS_CATCH;
	}
	public String getALERT_COMPARE_PROCESS_STATUS_ALL() {
		return ALERT_COMPARE_PROCESS_STATUS_ALL;
	}
	public void setALERT_COMPARE_PROCESS_STATUS_ALL(String aLERT_COMPARE_PROCESS_STATUS_ALL) {
		ALERT_COMPARE_PROCESS_STATUS_ALL = aLERT_COMPARE_PROCESS_STATUS_ALL;
	}
	
	
	
	
	
	
}

